version: 0.2

phases:
  install:
    commands:
      - yum install jq
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Building Flask app
  post_build:
    commands:
      - echo Pushing the Docker images to ECR
artifacts:
  files:
    - appspec.yml
    - taskdef.json
    - image*.json
